/**
 * Core TypeScript types for @syncforge/core.
 *
 * All interfaces mirror the server-side Elixir schemas
 * (User, Room, Comment, Reaction, Notification, Activity)
 * and the Phoenix Channel event payloads.
 */

// ---------------------------------------------------------------------------
// Domain entities
// ---------------------------------------------------------------------------

export interface User {
  id: string;
  name: string;
  avatar_url?: string | null;
}

export interface PresenceUser extends User {
  status: string;
  joined_at: string;
  cursor_visible?: boolean;
  updated_at?: string;
}

export interface Comment {
  id: string;
  body: string;
  anchor_id?: string | null;
  anchor_type?: "element" | "selection" | "point" | null;
  position?: Record<string, unknown> | null;
  resolved_at?: string | null;
  user_id: string;
  room_id: string;
  parent_id?: string | null;
  inserted_at: string;
  updated_at: string;
}

export interface Reaction {
  id: string;
  emoji: string;
  comment_id: string;
  user_id: string;
  inserted_at: string;
}

export interface Notification {
  id: string;
  type:
    | "comment_mention"
    | "comment_reply"
    | "comment_resolved"
    | "reaction_added"
    | "room_invite"
    | "user_joined";
  payload: Record<string, unknown>;
  read_at?: string | null;
  actor_id?: string | null;
  room_id?: string | null;
  inserted_at: string;
}

export interface Activity {
  id: string;
  type:
    | "user_joined"
    | "user_left"
    | "comment_created"
    | "comment_resolved"
    | "comment_deleted"
    | "reaction_added"
    | "reaction_removed";
  actor_id?: string | null;
  subject_id?: string | null;
  subject_type?: string | null;
  payload: Record<string, unknown>;
  room_id: string;
  inserted_at: string;
}

// ---------------------------------------------------------------------------
// Real-time payloads (match RoomChannel broadcasts)
// ---------------------------------------------------------------------------

export interface CursorPosition {
  user_id: string;
  name: string;
  color: string;
  x: number;
  y: number;
  element_id?: string;
  timestamp: number;
}

export interface Selection {
  user_id: string;
  name: string;
  color: string;
  selection: unknown;
  element_id?: string;
  timestamp: number;
}

export interface TypingEvent {
  user_id: string;
}

// ---------------------------------------------------------------------------
// Room state (pushed on join)
// ---------------------------------------------------------------------------

export interface RoomState {
  comments?: Comment[];
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Connection / client config
// ---------------------------------------------------------------------------

export type ConnectionState =
  | "disconnected"
  | "connecting"
  | "connected"
  | "errored";

export interface ClientOptions {
  /** WebSocket endpoint, e.g. "wss://api.syncforge.io/socket" */
  endpoint: string;
  /** Auth token generated by Phoenix.Token */
  token: string;
  /** Additional params sent on socket connect */
  params?: Record<string, unknown>;
  /** Logger function for debug output */
  logger?: (kind: string, msg: string, data?: unknown) => void;
}

export interface JoinRoomOptions {
  /** Additional params sent when joining the channel */
  params?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Event maps (used by TypedEventEmitter)
// ---------------------------------------------------------------------------

export interface ClientEventMap {
  connected: undefined;
  disconnected: { reason?: string };
  error: { message: string };
}

export interface RoomEventMap {
  joined: { response: Record<string, unknown> };
  left: undefined;
  error: { reason: string };

  // Presence
  "presence:sync": { users: PresenceUser[] };
  "presence:join": { user: PresenceUser };
  "presence:leave": { user: PresenceUser };

  // Cursors
  "cursor:update": CursorPosition;

  // Selections
  "selection:update": Selection;

  // Typing
  "typing:start": TypingEvent;
  "typing:stop": TypingEvent;

  // Comments
  "comment:created": { comment: Comment };
  "comment:updated": { comment: Comment };
  "comment:deleted": { comment_id: string };
  "comment:resolved": { comment: Comment };

  // Reactions
  "reaction:added": { reaction: Reaction };
  "reaction:removed": {
    reaction_id: string;
    comment_id: string;
    user_id: string;
    emoji: string;
  };

  // Activity
  "activity:created": { activity: Activity };

  // Room state (on join)
  "room:state": RoomState;
}

export interface NotificationEventMap {
  "notification:new": Notification;
  "notification:unread_count": { count: number };
}
